[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
lazy_static = "1.4.0"
mysql = "20.1.0"
chrono = "0.4"